### ISSUE TITLE
Проверить ДЗ 

### ISSUE THREAD

**Issue by AleksandrNagovitsyn** [AleksandrNagovitsyn/Ulmart#1]
@coursar у меня несколько вопросов возникло, при выполнении ДЗ: 
1. Почему класс не реализующий все методы интерфейса должен быть абстрактным? 
2. Для чего создаются объекты с типом интерфейса?
3. Я переопределил toString в родителе, потом в дочерних классах (в них переопределились только поля, которых не было в родителе). В результате, при вызове toString к объектам дочерних классов, поля родителя не  показывались, показывались только поля, объявленные или инициализированные в конкретном классе (например, category и smartphone для класса Phone). 

Мне пришлось сделать так 
https://github.com/AleksandrNagovitsyn/Ulmart/blob/ecf841027d814eab17e6f0fa8cee33caf089e51e/src/main/java/ru/itprk/model/Phone.java#L23-L34

То есть руками toString переписывать. Есть вариант проще? Или я неправильно делал что-то?

4. Почему если я объявляю метод в интерфейсе, имплементирующем компаратор, и добавляю в метод модификатор static мне выдает ошибку? Почему так нельзя делать?

**Comment by coursar** [comment]
1. Потому в интерфейсе описываются абстрактные методы, если ваш класс все их не реализовал, значит сам стал абстрактным
2. Для того, чтобы использовать их там, где нужен только интерфейс. Для сортировки, нужен объект, удовлетворяющий интерфейсу Comparator, больше ничего коллекции о вашем объекте знать не надо (даже если он умеет что-то ещё)
3. Там есть другой конструктор в IDEA, который позволяет вызвать `super.toString()` (см. скриншот), таким образом, вам распечатаются и все поля родителя
4. Потому что в интерфейсе этот метод без модификатора `static`, значит в вашем классе он тоже не может быть `static`.

**Comment by coursar** [comment]
![Screenshot from 2019-10-28 12-03-38](https://user-images.githubusercontent.com/3601892/67665583-0a437f00-f97b-11e9-92ea-15e2a2497819.png)
